### ISSUE TITLE
Use cases diagram

### ISSUE THREAD

**Issue by hiusnguyen201** [hiusnguyen201/cps-market#11]

**Comment by hiusnguyen201** [comment]
https://drive.google.com/file/d/1MriHjqgY-nBYvMvSvPnSNTJFclsTzH2h/view?usp=sharing

**Comment by Thuongbsls2004** [comment]
https://drive.google.com/file/d/1Z6aQsB_LkoDjo76iIQ-aUtldfR3heD4V/view?usp=sharing

**Comment by hiusnguyen201** [comment]
> https://drive.google.com/file/d/1Z6aQsB_LkoDjo76iIQ-aUtldfR3heD4V/view?usp=sharing

Sơ sài
