### ISSUE TITLE
Use case description

### ISSUE THREAD

**Issue by hiusnguyen201** [hiusnguyen201/cps-market#60]

**Comment by Thuongbsls2004** [comment]
[UseCaseDescriptionCPS.docx](https://github.com/hiusnguyen201/cps-market/files/14878526/UseCaseDescriptionCPS.docx)

**Comment by Thuongbsls2004** [comment]
[UseCaseDescriptionCPS.docx](https://github.com/hiusnguyen201/cps-market/files/14884031/UseCaseDescriptionCPS.docx)
fix platform -> page

**Comment by Thuongbsls2004** [comment]
https://drive.google.com/drive/folders/1EKt0tpHhkwEX41Kx9vUw_JrjiF7UHVjO?usp=sharing
UCDescription & Activity Diagram & Sequence Diagram

**Comment by hiusnguyen201** [comment]
Vinh:
https://drive.google.com/drive/folders/1yn45QuRj1l7ScHXcAKqTS6KXfjh6Nvrl

**Comment by hiusnguyen201** [comment]
![image](https://github.com/hiusnguyen201/cps-market/assets/112693497/591ac374-25c4-44ae-8dc3-8ffc62383be3)

**Comment by hiusnguyen201** [comment]
![Image](https://github.com/hiusnguyen201/cps-market/assets/112693497/6218378a-0986-4541-8e31-b418e580afb8)

**Comment by hiusnguyen201** [comment]
![Image](https://github.com/hiusnguyen201/cps-market/assets/112693497/102676f7-ae14-41ba-acac-a4003b7310f0)

**Comment by hiusnguyen201** [comment]
![image](https://github.com/hiusnguyen201/cps-market/assets/112693497/0b6c886e-5aba-4690-9c3f-146e85084745)
