### ISSUE TITLE
Authentication (local login & 2FA)

### ISSUE THREAD

**Issue by hiusnguyen201** [hiusnguyen201/cps-market#8]
Router: /auth
Example : 
- Login: /auth/login
- Otp: /auth/otp

**Comment by minbaby01** [comment]
![image](https://github.com/hiusnguyen201/cps-market/assets/30135804/2dbb8be0-664c-458f-af7f-67423dc81df9)

**Comment by minbaby01** [comment]
![image](https://github.com/hiusnguyen201/cps-market/assets/30135804/54cd16a2-d06b-4a16-992d-886f7d475139)
