### ISSUE TITLE
Manage users

### ISSUE THREAD

**Issue by hiusnguyen201** [hiusnguyen201/cps-market#9]
Router: /admin/users
Example :

- get: /admin/users
- create: /admin/users/create
- edit: /admin/users/{id}
- delete: /admin/users

**Comment by Thuongbsls2004** [comment]
![Screenshot 2024-03-01 183132](https://github.com/hiusnguyen201/cps-market/assets/126715357/e2cced2b-999d-466c-b284-e2ab9703623e)
![Screenshot 2024-03-01 183234](https://github.com/hiusnguyen201/cps-market/assets/126715357/9db10793-a883-4a8f-88bc-2027d51ec2eb)
![Screenshot 2024-03-01 183242](https://github.com/hiusnguyen201/cps-market/assets/126715357/56ccdca7-aa00-432f-9041-62d709eddd2d)

**Comment by Thuongbsls2004** [comment]
![image](https://github.com/hiusnguyen201/cps-market/assets/126715357/46114b21-bf32-4636-a826-9c8631aa7caf)

**Comment by hiusnguyen201** [comment]
![Image](https://github.com/hiusnguyen201/cps-market/assets/112693497/34a02d29-4e72-4d68-b98e-2d5e1f0ac89b)
